### ISSUE TITLE
Superblock spreadsheet

### ISSUE THREAD

**Issue by ohcee** [Veil-Project/veil-project.github.io#60]
Needs to be updated with current data. Its some months behind.
![Screenshot 2023-05-10 at 4 17 17 PM](https://github.com/Veil-Project/veil-project.github.io/assets/46406370/a4b54843-0077-467b-8778-bf94b3d52d47)

**Comment by ohcee** [comment]
To add it might be nice to know where the monthly superblock goes. Like as far who gets what from the superblock as far as the "team". How much do they get and for what? Or is the majority just hodled. What's the plan for these funds? Why are they not being used? If I was new a was looking into this it would be red flag. 

I myself who has been here a while, don't even know these answers.

**Comment by seanPhill** [comment]
The majority is HODLed. The biggest costs presently are the hosting costs for various servers our infrastructure, and while that is being compensated, even that is not being sold on the market at the moment, because of the low coin price. It doesn't make any sense to sell at current prices. Sure, if we had the early to mid 2019 prices (which would give us tens and tens of millions of dollars valuation) the budget could go a long way. Not just throwing it around. We have great plans for when the budget, monthly and saved, will be able to buy a lot of work, development and marketing.

**Comment by seanPhill** [comment]
That being said, the budget is done in basecoins, so the monthly disbursements can be seen on a block explorer. It just doesn't have names attached to the addresses, as that's not possible in the blockchain.

**Comment by ohcee** [comment]
Thanks for that. Maybe that wouldn't be beneficial to add this to the website? Or maybe it would for true transparency. I totally agree on not selling now.

**Comment by seanPhill** [comment]
I updated the spreadsheet, but need to do it again, _and then_ merge this.

**Comment by seanPhill** [comment]
Updated the spreadsheet in PR#73
